// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function UploadToServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['sftp']['SftpService']['UploadToServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UploadToServerWithKey(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['sftp']['SftpService']['UploadToServerWithKey'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
